baseURL = "https://robinfrossard.github.io/labveilletech/"
languageCode = "en-us"
title = "Personal Digital Garden"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']
  enableSearch = true


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 2
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3



[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/RobinFrossard'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/robin-frossard-361640223/'
  weight = 3
[[menu.social]]
  name = 'Email'
  url = 'mailto:robin.frossard1@hes-so.ch'
  weight = 8



# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
